spring:
  application:
    name: cms
  datasource:
    url: jdbc:postgresql://localhost:5432/cms_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

# OpenAPI/Swagger UI: http://localhost:8080/swagger-ui.html
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
